### ISSUE TITLE
Implement user logging

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps#267]
It would be nice to give the user the possibility to log process activity into the database. Naturally, this would be far more interesting than just using the old text file. With SQLAlchemy this would be a major improvement for the users debugging/tuning their processes.

One of the ways to this would be to add a log() method to the Process class. Another possibility is to pass an argument called logger to the _handler() method.

**Comment by dbyrns** [comment]
Maybe I'm wrong but every call to the WPSResponse update_status function is stored into the database. If rather than updating the message it could be appended we could store the entire processing log. Is that what you would like to do? I would be very interested to obtain the full processing log rather than polling the process continuously and try to catch every single update_status message. For this, the xml status file might contain the full log when the process completes or fails.

**Comment by ldesousa** [comment]
Only the last status of a running process is stored in the database. As it stands, the user must implement his own logging to track the activity of a process.

**Comment by jachym** [comment]
passing logger might be more flexible, handler does not have to be method
of the process class. it can remain independent, right?
j

**Comment by dbyrns** [comment]
I understand that currently only the last status is stored in the DB. I was suggesting to modify the way it works so that every status are persisted. But using an independant logger is indeed more flexible and would allow to log more things than just "status". 
What do you thing about the proposition to find a way for the caller to retrieve the full log (No matter how it is produced)  rather than just the last status?

**Comment by ldesousa** [comment]
@dbyrns It would be possible, but that is outside the WPS standard. Also, as a process developer, I prefer not to have other users going through my logs.

**Comment by dbyrns** [comment]
Ok thank you for your clarification. In the end I think that what I wish (Being able to retrieve all messages send to the update_status function from the process) is unrelated with this issue which is more about internal dev logs which indeed should not be public.

**Comment by ldesousa** [comment]
With issue #282 implemented, PyWPS now provides a more powerful and practical debugging mechanism. Therefore user logging is no longer needed.
